### ISSUE TITLE
Brian's sida

### ISSUE THREAD

**Issue by Buriiboo** [SandraAnder/Hackaton_gruppEton#1]
Vad ska den innehålla?

**Comment by SandraAnder** [comment]
En presentation och tre punkter med vad man är bra på.

**Comment by Buriiboo** [comment]
+ 1 bild.

**Comment by Buriiboo** [comment]
![rick james b](https://github.com/SandraAnder/Hackaton_gruppEton/assets/143494655/f8ff1c92-c0ab-4ff2-a1dc-f52eedaad5a6)
